module.exports = {
  black: '#101010',
  dimmed: 'rgba(16, 16, 16, .6)',
  grayFont: '#999999',
  grayDisabled: '#989898',
  gray: '#a0a0a0',
  gray10: '#a6a6a6', // web-carrier 에서 추가.
  gray20: '#bbbbbb', // web-carrier 에서 추가.
  gray30: '#666666',
  gray40: '#333333', //web-carrier 에서 추가.
  gray50: '#101010', //web-carrier 에서 추가.
  gray60: '#bfbfbf',
  gray70: '#d0d0d0',
  gray80: '#dfdfdf',
  gray90: '#eeeeee', // web-carrier 에서 추가.
  disabled: '#cccccc',
  divideLine: '#f0f0f0',
  divideArea: '#f2f2f2',
  evenList: '#f5f5f5',
  white: '#ffffff',
  lightDisabled: 'rgb(242, 242, 242)',
  yellow: '#ffbc00',
  borderYellow: '#fdc324',
  eggYellow: '#fcecc0',
  navy: '#373d45',
  red: '#ef5350',
  main: '#ffbc00',
  secondary: '#373d45',
  error: '#fd6060',
  transparent: 'transparent',
  background: 'var(--background)',
  subBackground: 'var(--subBackground)',
  surface: 'var(--surface)',
  floatingBackground: 'var(--floatingBackground)',
  lightLine: 'var(--lightLine)',
  darkLine: 'var(--darkLine)',
  subBorder: 'var(--subBorder)',
  mainText: 'var(--mainText)',
  subText: 'var(--subText)',
  episodeBorder: 'var(--episodeBorder)',
  commentText: 'var(--commentText)',
  commentBorder: 'var(--commentBorder)',
  commentTextForm: 'var(--commentTextForm)',
  disabledCommentTextForm: 'var(--disabledCommentTextForm)',
  disabledButton: 'var(--disabledButton)',
  disabledButtonBackground: 'var(--disabledButtonBackground)',
  buttonBorder: 'var(--buttonBorder)',
  activeButton: 'var(--activeButton)',
  activeButtonBackground: 'var(--activeButtonBackground)',
  link: 'var(--link)',
  disabledLink: 'var(--disabledLink)',
  noticeBackground: 'var(--noticeBackground)',
  divider: 'var(--divider)',
  lastEpisode: 'var(--lastEpisode)',
};
